[options]
; Rutas de addons: ruta predeterminada de Odoo y la carpeta extra-addons
addons_path = 	/usr/lib/python3/dist-packages/odoo/addons, 
				/mnt/extra-addons

; Parámetros de conexión a la base de datos
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo

; Archivo de log
# logfile = /var/log/odoo/odoo-server.log

; Parámetros adicionales
limit_time_real = 3600
